### ISSUE TITLE
Upload evidence connecting frontend and backend 

### ISSUE THREAD

**Issue by AmjadShubbar** [bahrain-bp/bqa-genai-challenge#35]
This page is for the university officer to upload the required evidence based on standards and indicators.
The progress bar steps represents the standards, and within each standard there are indicators; these indicators are represented as upload sections.

-The required standards and indicator names were retrieved through an API from dynamoDB.

-The standards and indicators are connected to the progress bar correctly.

-I connected the uploading section through an API, and files were uploaded successfully.

**Comment by FatimaJ20** [comment]
- The required standards and indicator names were retrieved through an API from dynamoDB.
- The standards and indicators are connected to the progress bar correctly.
- I connected the uploading section through an API, and files were uploaded successfully.


- Now I'm facing 2 issues:
1- When the user uploads something in the first step and moves to the next step whatever was uploaded in the UI disappears.
2- Therefore, I need to retrieve the uploaded files from the s3 and display them again in the UI; but right now it is not differentiating between which file belongs to which indicator (only which file belongs to which standard).

So I came across 2 solutions- one of them being that when a file gets uploaded I add something to the file name that will associate it to the indicator it belongs to. 
or create an extra subfolder for each indicator.
I'm looking into both options and seeing which one is suitable; I have also discussed this issue with the team and we agreed that both solutions are good.

**Comment by FatimaJ20** [comment]
Hello @cerashdan, I can upload files successfully in my s3 bucket (uni-artifacts). 
In uni-artifacts a file gets created for the specific standard step we are in and then for each upload section (indicator) a file gets created within its designated standard. 

This is the upload structure I have right now (standard1/indicator1/file.pdf).

I'm currently facing a problem with fetching the uploaded folders and posting them back in the page. The reason why I want to do that is that when I upload files in step 1 and move to step 2 and then move back to step 1 the files I uploaded vanish from the UI. Therefore, I want to retrieve them in case the user wants to revise the folders he uploaded, or even delete them from both the UI and S3 bucket.

For deleting them I'm working on creating a lamda function, that will be in another task/feature.

The frontend page I'm working in is UploadEvidence.tsx
The upload lamda function s3Upload.ts
The retrieve lamda retrieveS3.ts
branch: 35-submit-as-draft-progressBar

Note: The code for fetching in UploadEvidence.tsx are commented out because I used 2 methods for fetching, both are not working.

**Comment by cerashdan** [comment]
@maalsaegh

**Comment by maalsaegh** [comment]
@FatimaJ20 What is the problem you're currently facing? Any specific error message?
What steps have you done to implement this feature? Any references/documentation?  

Generally, you can use the GetObject S3 API call to access files stored in your S3 bucket using the full key name for the object. For your reference: https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html

**Comment by FatimaJ20** [comment]
This issue has been resolved, and the task is completed!!
